cmake_minimum_required(VERSION 3.0)
PROJECT(cec17)
set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -O2")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2")
ADD_EXECUTABLE(test "test.cc")
ADD_EXECUTABLE(testrandom "testrandom.cc")
ADD_EXECUTABLE(testsolis "testsolis.cc")
ADD_EXECUTABLE(testlca "testlca.cc")
ADD_EXECUTABLE(testlcasw "testlcasw.cc")
ADD_EXECUTABLE(testlcachc "testlcachc.cc")
ADD_EXECUTABLE(testlcamulti "testlcamulti.cc")
ADD_EXECUTABLE(testde "testde.cc")
ADD_EXECUTABLE(testpso "testpso.cc")
ADD_LIBRARY("cec17_test_func" SHARED "cec17_test_func.c" "cec17.c")
TARGET_LINK_LIBRARIES(test "cec17_test_func")
TARGET_LINK_LIBRARIES(testrandom "cec17_test_func")
TARGET_LINK_LIBRARIES(testsolis "cec17_test_func")
TARGET_LINK_LIBRARIES(testlca "cec17_test_func")
TARGET_LINK_LIBRARIES(testlcasw "cec17_test_func")
TARGET_LINK_LIBRARIES(testlcachc "cec17_test_func")
TARGET_LINK_LIBRARIES(testlcamulti "cec17_test_func")
TARGET_LINK_LIBRARIES(testde "cec17_test_func")
TARGET_LINK_LIBRARIES(testpso "cec17_test_func")
